In [78]:
import pandas as pd
import numpy as np
import plotly.express as px

In [79]:
np.random.seed(23)

In [80]:
arr_11 = np.array([0,0,0])
arr_12 = np.array([[1,0,0],[0,1,0],[0,0,1]])
sample_1 = np.random.multivariate_normal(arr_11, arr_12, 20)

In [81]:
df_1 = pd.DataFrame(sample_1, columns = ['feature_1','feature_2','feature_3'])
df_1['target'] = 1

In [82]:
arr_21 = np.array([1,1,1])
arr_22 = np.array([[1,0,0],[0,1,0],[0,0,1]])
sample_2 = np.random.multivariate_normal(arr_21, arr_22, 20)

In [83]:
df_2 = pd.DataFrame(sample_2, columns = ['feature_1','feature_2','feature_3'])
df_2['target']=0

In [84]:
df = df_1
df = df.append(df_2,ignore_index = True)
df = df.sample(40)

/var/folders/k5/m5y73k4n41d0_vmt2kk4st180000gn/T/ipykernel_25612/936534777.py:2: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.



In [85]:
fig = px.scatter_3d(df, x=df['feature_1'], y=df['feature_2'], z=df['feature_3'],color = df['target'].astype('str'))
fig.update_traces(marker=dict(size=12,
                              line=dict(width=2,
                                       color='DarkSlateGrey')),
                 selector=dict(mode='markers'))

In [86]:
# step_1 : apply standard scaller
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
df.iloc[:,0:3] = scaler.fit_transform(df.iloc[:,0:3])

In [87]:
# step_2 : Find Covariance Matrix
cov_mat = np.cov([df.iloc[:,0],df.iloc[:,1],df.iloc[:,2]])
print(cov_mat)

[[1.02564103 0.20478114 0.080118  ]
 [0.20478114 1.02564103 0.19838882]
 [0.080118   0.19838882 1.02564103]]


In [88]:
# step_3 finding EV and EVs
ei_val, ei_vec = np.linalg.eig(cov_mat) 
print(ei_val)

[1.3536065  0.94557084 0.77774573]


In [89]:
print(ei_vec)

[[-0.53875915 -0.69363291  0.47813384]
 [-0.65608325 -0.01057596 -0.75461442]
 [-0.52848211  0.72025103  0.44938304]]


In [90]:
%pylab inline
from matplotlib import pyplot as plt
from mpl_toolkits.mplot3d import Axes3D, proj3d
from matplotlib.patches import FancyArrowPatch

%pylab is deprecated, use %matplotlib inline and import the required libraries.
Populating the interactive namespace from numpy and matplotlib


In [91]:
pc = ei_vec[0:2]
pc

array([[-0.53875915, -0.69363291,  0.47813384],
       [-0.65608325, -0.01057596, -0.75461442]])

In [92]:
transform_df = np.dot(df.iloc[:,0:3],pc.T)

In [93]:
new_df = pd.DataFrame(transform_df, columns=['pc_1','pc_2'])
new_df['target'] = df['target'].values 

In [94]:
new_df.shape

(40, 3)

In [95]:
new_df['target'] = new_df['target'].astype('str')

In [96]:
fig = px.scatter(x=new_df['pc_1'],y=new_df['pc_2'],color=new_df['target'])
fig.update_traces(marker=dict(size=12,line=dict(width=2,color='DarkSlateGrey')),selector=dict(mode='markers'))
fig.show()