In [1]:
import pickle as pk
import numpy as np

In [2]:
ohe_sex = pk.load(open('ohe_sex.pkl','rb'))
ohe_embarked = pk.load(open('ohe_embarked.pkl','rb'))
clf = pk.load(open('cle.pkl','rb'))

In [3]:
test_input = np.array([2, 'male', 31.0, 0, 0, 10.5, 'S'], dtype=object).reshape(1,7)

In [4]:
test_input

array([[2, 'male', 31.0, 0, 0, 10.5, 'S']], dtype=object)

In [5]:
test_input_sex = ohe_sex.transform(test_input[:,1].reshape(1,1))
test_input_embarked = ohe_embarked.transform(test_input[:,-1].reshape(1,1))

/Users/kunalborade/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [6]:
test_input_embarked

array([[0., 0., 1.]])

In [7]:
test_input_age = test_input[:,2].reshape(1,1)

In [8]:
test_input_transform = np.concatenate((test_input[:,[0, 3, 4, 5]], test_input_age, test_input_sex, test_input_embarked),axis=1)

In [9]:
test_input_transform.shape

(1, 10)

In [10]:
clf.predict(test_input_transform)

array([1])